name: Firebase Deploy

on:
  push:
    branches:
      - main  # Run this workflow on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set the working directory (if your package.json is in a subfolder)
      - name: Set working directory
        working-directory: ./subfolder-name  # Set this to the folder where your package.json is located

      # Step 3: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 4: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 5: Run your build script
      - name: Run build
        run: npm run build

      # Step 6: Deploy to Firebase Hosting
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_KIDS_CHATGPT }}"
          channelId: live
