name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # This triggers deployment on pushes to the 'main' branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Set up Node.js (Use Node.js 18 for Firebase CLI compatibility)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Node.js 18 or higher is required for Firebase CLI

      # Step 3: Install Dependencies (if needed)
      - name: Install Dependencies
        run: npm install  # If you have dependencies to install (optional)

      # Step 4: Deploy to Firebase Hosting
      - name: Deploy to Firebase Hosting
        run: |
          npm install -g firebase-tools
          firebase deploy --token ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KIDS_CHATGPT }} --project kids-chatgpt
