name: Firebase Deploy

on:
  push:
    branches:
      - main  # This triggers the workflow when changes are pushed to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment (using Node.js 18)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Set this to at least version 18

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run the build script (if needed)
      - name: Run build
        run: npm run build

      # Step 5: Deploy to Firebase Hosting
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_KIDS_CHATGPT }}"
          channelId: live
